name: Python

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'ttx_diff/**'
      - '.github/workflows/ttx-diff.yml'
    tags:
      - 'ttx-diff-v*'
  pull_request:
    paths:
      - 'ttx_diff/**'
      - '.github/workflows/ttx-diff.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install package with dev dependencies
        working-directory: ttx_diff
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run tests
        working-directory: ttx_diff
        run: |
          uv run pytest -v

      - name: Test CLI help
        working-directory: ttx_diff
        run: |
          uv run ttx-diff --help

  lint:
    name: Lint and format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install package with dev dependencies
        working-directory: ttx_diff
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Check package builds
        working-directory: ttx_diff
        run: |
          uv pip install build
          uv run python -m build

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ttx-diff-v')

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install build dependencies
        run: uv pip install --system build

      - name: Build package
        working-directory: ttx_diff
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ttx_diff/dist/

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ttx-diff-v')
    environment:
      name: pypi
      url: https://pypi.org/p/ttx-diff
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  publish-test-pypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ttx-diff-v')
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ttx-diff
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
